const numero1 = 20;
const numero3 = 30;

console.log(numero1);
//*intenta hacer lo sgte y si no puede pasa al catch
try {
	console.log(numero2);
} catch (error) {
	console.log(error);
}
console.log(numero3);
